apiVersion: apps/v1
kind: Deployment

metadata:
  name: capstone-cluster
  labels:
    app: capstone

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: nicomwang/udacity-capstone:v1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service

metadata:
  name: capstone-lb
  labels:
    app: capstone

spec:
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
